### ISSUE TITLE
التعديلات المطلوبه لشاشات برنامج الوحدات المحموله

### ISSUE THREAD

**Issue by osamamohammed731** [MaisrForAdvancedSystems/Sohag#2]
**النموذج** 
[المقترحات.pdf](https://github.com/MaisrForAdvancedSystems/Sohag/files/1471996/default.pdf)

**Comment by HassanAbdelzaher** [comment]
Osama please identify the required modification in separate file

**Comment by osamamohammed731** [comment]
التعديلات المقترحه بناءاً على طلب شركة المياه بسوهاج
![1](https://user-images.githubusercontent.com/29673050/33184580-f0af5cbe-d085-11e7-944b-796894059ab9.jpg)
![2](https://user-images.githubusercontent.com/29673050/33184835-7a64bed0-d087-11e7-92d7-94ffb8f6d6b7.jpg)
![3](https://user-images.githubusercontent.com/29673050/33184634-3a3c3334-d086-11e7-9ef9-edb078e9eb48.jpg)
![4](https://user-images.githubusercontent.com/29673050/33184635-3a776b3e-d086-11e7-9df0-f289303e4b3f.jpg)
![5](https://user-images.githubusercontent.com/29673050/33184637-3b5cfdb6-d086-11e7-8b20-f44700948ae1.jpg)
![6](https://user-images.githubusercontent.com/29673050/33184653-4e4adef2-d086-11e7-9f99-d253e0a7460c.jpg)
![7](https://user-images.githubusercontent.com/29673050/33184655-51fb4226-d086-11e7-88c1-57f53a53916c.jpg)
![8](https://user-images.githubusercontent.com/29673050/33184656-52238e16-d086-11e7-8280-1c8e1f6f1cdc.jpg)
![9](https://user-images.githubusercontent.com/29673050/33184657-5270cd20-d086-11e7-8000-40cb00267daf.jpg)
![10](https://user-images.githubusercontent.com/29673050/33184658-52c56d94-d086-11e7-866e-c6d0d549cf08.jpg)
![11](https://user-images.githubusercontent.com/29673050/33184660-589398e0-d086-11e7-95af-76236ddc509e.jpg)
![12](https://user-images.githubusercontent.com/29673050/33184662-58b83aba-d086-11e7-90ba-05b39a43dc42.jpg)
![13](https://user-images.githubusercontent.com/29673050/33184663-59077f62-d086-11e7-94bd-dac2cb9db0c8.jpg)
![14](https://user-images.githubusercontent.com/29673050/33184665-5958377c-d086-11e7-9ba8-e0bfa2a91327.jpg)
